name: Test

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Grant execute permission for gradlew # gradlew 파일에 실행 권한 부여
        run: chmod +x gradlew # gradlew 파일에 실행 권한을 부여한다.

        # 1. Java 17 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 2. application.properties 파일 생성
      - name: make application.properties
        run: |
          mkdir -p ./src/test/resources
          cd ./src/test/resources
          touch ./application.properties
          echo "${{ secrets.DEV_TEST_PROPERTIES }}" > ./application-test.properties
        shell: bash

        # Gradle Test를 실행한다
      - name: Test with Gradle
        run: ./gradlew --info test

        # Test 후 Report 생성
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: '**/build/test-results/test/TEST-*.xml'